/**
 * Predefined knowledge base for common questions about Travio.
 */
const knowledgeBase = [
  {
    id: "use_travio",
    keywords: [
      "how do i use travio",
      "how to use travio",
      "how does travio work",
      "what is travio",
      "travio guide"
    ],
    answer: "Travio is a personalized travel planner. You can start by customizing your travel preferences on the Preferences page (accessed by clicking 'Start Planning' on the Home page), and Travio AI will generate curated destination recommendations for you. You can then save your favorite destinations to your Wishlist, generate customized itineraries, and create packing lists for your trips."
  },
  {
    id: "generate_recommendations",
    keywords: [
      "generate recommendations",
      "generate recommendation",
      "how to generate recommendations",
      "how do i generate recommendations",
      "create recommendations",
      "get recommendations"
    ],
    answer: "To generate personalized destination recommendations, click the 'Start Planning' button on the Home page (or click 'Explore' in the navigation bar to access the preferences form). Adjust your budget, duration, travel style, season, number of travelers, and interests, then click 'Generate Recommendations'. Travio AI will instantly recommend matching destinations for you."
  },
  {
    id: "explore_page",
    keywords: [
      "what is the explore page",
      "what is explore page",
      "explore page",
      "how does the explore page work",
      "about explore page"
    ],
    answer: "The Explore page (accessed by clicking 'Explore' in the navigation bar) shows the curated recommendations generated by Travio AI based on your preferences. From here, you can click on any destination card to view its details, maps, weather, travel tips, and signature highlights."
  },
  {
    id: "save_destination",
    keywords: [
      "save a destination",
      "save destination",
      "saving destinations",
      "how to save a destination",
      "add to wishlist",
      "save to wishlist",
      "wishlist a destination",
      "saving a destination"
    ],
    answer: "When viewing any destination's details page, click the 'Save to wishlist' button in the hero banner. The destination will be saved to your personal wishlist, which you can access anytime by clicking the profile icon (👤) in the navigation bar and selecting 'My Wishlist' (or visiting /wishlist)."
  },
  {
    id: "itinerary",
    keywords: [
      "see my itinerary",
      "where is my itinerary",
      "find my itinerary",
      "itinerary page",
      "view my itinerary",
      "where can i see my itinerary",
      "access my itinerary",
      "my itinerary"
    ],
    answer: "You can view your generated itineraries by clicking the 'Itinerary' tab in the navigation bar. This page displays day-by-day activity plans, custom travel durations, and schedules for your saved destinations."
  },
  {
    id: "packing_list",
    keywords: [
      "what is the packing list",
      "what is packing list",
      "where is the packing list",
      "packing list",
      "packing page",
      "check my packing list",
      "checklist"
    ],
    answer: "The Packing page (accessible via the 'Packing' tab in the navigation bar) provides an AI-generated checklist of recommended travel essentials customized for your planned trip. You can check off items as you pack, add new custom items, and track your packing progress before you travel."
  },
  {
    id: "change_preferences",
    keywords: [
      "change my travel preferences",
      "change travel preferences",
      "change travel preference",
      "how to change travel preferences",
      "how do i change travel preferences",
      "edit travel preferences",
      "update my preferences",
      "change preferences",
      "update travel preferences"
    ],
    answer: "To change your travel preferences, click 'Explore' (or navigate to /preferences) to open the travel preferences form. Adjust your budget, duration, travel style, season, travelers, or interests, and submit the form to update your recommendations."
  },
  {
    id: "ai_recommendation_meaning",
    keywords: [
      "what does the ai recommendation mean",
      "what does ai recommendation mean",
      "meaning of ai recommendation",
      "ai recommendation score",
      "ai recommendation mean",
      "recommendation score mean"
    ],
    answer: "The AI recommendation score indicates how well a destination matches your travel preferences. The closer the match is to 100%, the more suitable the destination is for your specified budget, duration, style, and interests."
  },
  {
    id: "atlas_capabilities",
    keywords: [
      "what can atlas help me with",
      "what can atlas help with",
      "what is atlas",
      "who is atlas",
      "what does atlas do",
      "how can atlas help"
    ],
    answer: "Atlas is your ultimate AI travel concierge! Atlas can guide you on how to use all the features of the Travio application, and also act as a travel expert to answer questions about destinations, local cuisines, attractions, travel tips, weather, and culture."
  },
  {
    id: "find_profile",
    keywords: [
      "where do i find my profile",
      "where is my profile",
      "find my profile",
      "access my profile",
      "my profile",
      "view profile"
    ],
    answer: "You can find your profile by clicking the profile icon (👤) on the right side of the navigation bar. Your Profile page contains your account details, travel stats, and links to view your saved wishlist destinations."
  },
  {
    id: "search_destinations",
    keywords: [
      "how do i search for destinations",
      "how to search for destinations",
      "search destinations",
      "search for destinations",
      "how do i search destinations",
      "searching for destinations"
    ],
    answer: "You can search for destinations by going to the Explore page after generating your recommendations, or by browsing the trending sections on the Home page. To discover new destinations matching specific criteria, you can adjust your travel preferences."
  }
];

/**
 * Normalizes the input message for matching.
 * @param {string} text
 * @returns {string}
 */
function normalizeText(text) {
  return text
    .toLowerCase()
    .trim()
    .replace(/[?.!,;:'"()\-]/g, "") // Remove punctuation
    .replace(/\s+/g, " ");          // Normalize whitespace
}

/**
 * Checks if the user's message is asking about a Travio feature.
 * Returns the predefined answer if matched, otherwise returns null.
 * @param {string} message 
 * @returns {string|null}
 */
export function getKnowledgeAnswer(message) {
  if (!message || typeof message !== "string" || message.trim() === "") {
    return null;
  }

  const normalizedInput = normalizeText(message);

  for (const item of knowledgeBase) {
    for (const keyword of item.keywords) {
      const normalizedKeyword = normalizeText(keyword);
      // We check if the input contains the keyword phrase
      if (normalizedInput.includes(normalizedKeyword)) {
        return item.answer;
      }
    }
  }

  return null;
}
