import React from "react";
import { Lightbulb, Info } from "lucide-react";

export default function TravelTipsCard({ tips }) {
  if (!tips || tips.length === 0) return null;

  return (
    <div className="planner-glass-card travel-tips-card">
      <div className="tips-header">
        <Lightbulb size={24} className="text-yellow" />
        <div>
          <h4>AI Personalized Travel Tips</h4>
          <p>Generated by Travio AI based on your traveler profile and destination customs.</p>
        </div>
      </div>

      <ul className="tips-bullet-list">
        {tips.map((tip, index) => (
          <li key={index} className="tip-bullet-item">
            <span className="tip-bullet-num">0{index + 1}</span>
            <div className="tip-bullet-content">
              <p>{tip}</p>
            </div>
          </li>
        ))}
      </ul>
      
      <div className="tips-footer-notice">
        <Info size={13} style={{ flexShrink: 0, marginTop: "2px" }} />
        <span>Double-check visa requirements and local health advisories prior to booking flights.</span>
      </div>
    </div>
  );
}
